base/urls.py
from django.urls import path
from base import views
    
app_name = 'base'

urlpatterns = [
    path('contact/', views.Contact.as_view(),name="contact"),
    path('about/', views.About.as_view(),name="about")
]

blog/urls.py
from django.urls import path
from blog.views import BlogListView, CategoryDetailView, BlogPostDetailView, tagged_view, UpdateCommentView, DeleteCommentView

app_name = 'blog'

urlpatterns = [
    path('blog_list/', BlogListView.as_view(), name='bloglist'),
    path('article/<slug:slug>/', BlogPostDetailView.as_view(), name='BlogPost-details'),
    path('tag/<slug:slug>/', tagged_view, name="tagged"),
    path('category/<slug:slug>/', CategoryDetailView, name='category_detail'),
    path('article/<int:pk>/update_comment/', UpdateCommentView.as_view(), name='Update_comment'),
    path('article/<int:pk>/delete_comment/', DeleteCommentView.as_view(), name='Delete_comment'),
]

courses/urls.py
from django.urls import path

from courses import views

app_name = 'courses'

urlpatterns = [
    path('', views.course ,name="index"),
    path('courses/', views.course_display, name='courses'),
    path('<slug:slug>/', views.course_detail, name='course_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

vortex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('base/',include('base.urls', namespace='base')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('basket/', include('basket.urls', namespace='basket')),
]

blog/models.py
from turtle import position
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User
from account.models import UserBase
from ckeditor.fields import RichTextField
from django.urls import reverse
from datetime import datetime, date
from cloudinary.models import CloudinaryField
#from portfolio.models import Category
from taggit.managers import TaggableManager

class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Category(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=100, null=True)
    
    def __str__(self):
        return self.name

class WriterProfile(models.Model):
    user = models.OneToOneField(
        UserBase,
        related_name='profile',
        on_delete=models.CASCADE,
    )
    image = CloudinaryField('image', null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    bio = models.CharField(max_length=2000)

    def __str__(self):
        return str(self.user)

#  image = models.ImageField(upload_to='images/', default='images/default.png')

# Create your models here.
class BlogPost(models.Model):
    image = CloudinaryField('image', null=True, blank=True)
    title = models.CharField(max_length=255)
    snippet = models.CharField(max_length=255, default='snippet test')
    slug = models.SlugField(unique=True, max_length=100, null=True)
    author = models.ForeignKey(WriterProfile, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content1 = RichTextField(blank=True, null=True)
    blog_quote = models.CharField(max_length=500, blank=True)
    content2 = RichTextField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    date_posted = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.title + '|' + str(self.author)

    def get_absolute_url(self):
        return reverse('BlogPost-details', kwargs={'slug': self.slug})

class BlogComment(models.Model):
    blogpost_connected =  models.ForeignKey(BlogPost, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(UserBase, on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.author) + ' , ' + self.blogpost_connected.title[:40]

    def get_absolute_url(self):
        return reverse('update_comment', kwargs={'pk': self.pk})

class About(models.Model):
    image = CloudinaryField('image', null=True, blank=True)
    title = models.CharField(max_length=255)
    content1 = RichTextField(blank=True, null=True)

    def __str__(self):
        return self.title + '|' 'about'

class Roles(models.Model):
    title = models.CharField(max_length=255)
    position = models.CharField(max_length=255)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from blog.models import BlogComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

class EditCommentForm(forms.ModelForm):
    class Meta:
        model = BlogComment
        fields = ('content',)

        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import BlogPost, BlogComment, Category
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib.messages.views import SuccessMessageMixin
from blog.forms import CommentForm, EditCommentForm
from taggit.models import Tag
from django.template.defaultfilters import slugify
from django.shortcuts import redirect

###------------------- Redirect to previous page Mixin
class RedirectToProviousMixin:
    default_redirect = '/'

    def get(self, request, *args, **kwargs):
        request.session['previous_page'] = request.META.get('HTTP_REFERER', self.default_redirect)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.session['previous_page']
###################################################################################################



#####------------------ Blog list view 
class BlogListView(ListView):
    model = BlogPost
    template_name = 'blog/blog.html'
    ordering = ['-date_posted']
    paginate_by = 8
#######################################################




#####-------------------- Blog Post Detail View
class BlogPostDetailView(DetailView):
    model = BlogPost
    template_name = 'blog/blogpost-details.html'


    def get_context_data(self, *args, **kwargs):
        cat_menu = Category.objects.all()
        context = super(BlogPostDetailView, self).get_context_data(*args, **kwargs)
        context["cat_menu"] = cat_menu
        context["BlogPosts"] =  BlogPost.objects.all().order_by('-date_posted')[:3]
        # context["related_items"] = self.object.tags.similar_objects()[:5]
        #context['commot_tags'] = BlogPost.objects.tags.most_common()[:4]
        comments_connected = BlogComment.objects.filter(blogpost_connected=self.get_object()).order_by('-date_posted')
        context['comments'] = comments_connected
        if self.request.user.is_authenticated:
            context['form_comment'] = CommentForm(instance=self.request.user)

        return context
    
    def post(self, request, *args, **kwargs):
        new_comment = BlogComment(content=request.POST.get('content'),
                                  author=self.request.user,
                                  blogpost_connected=self.get_object())
        new_comment.save()
        return self.get(self, request, *args, **kwargs)
###################################################################################################


def tagged_view(request, slug):
    tag = get_object_or_404(Tag, slug=slug)
    common_tags = BlogPost.tags.most_common()[:4]
    posts = BlogPost.objects.filter(tags=tag)
    context = {
        'tag':tag,
        'posts':posts,
        'common_tags':common_tags,
    }
    return render(request, 'tagged.html', context)


#######----------------- Category Detail View
##def CategoryDetailView(request, cats):
 #   category_posts = BlogPost.objects.filter(category=cats.replace('-', ' '))
  #  return render(request, 'category_detail.html',
   #               {'cats': cats.title().replace('-', ' '), 'category_posts': category_posts})
###################################################################################################

def CategoryDetailView(request, slug):
    cat = get_object_or_404(Category, slug=slug)
    #common_tags = BlogPost.tags.most_common()[:4]
    posts = BlogPost.objects.filter(category=cat)
    context = {
        'cat':cat,
        'posts':posts,
        #'common_tags':common_tags,
    }
    return render(request, 'category_detail.html', context)







#########---------------- Delete Comment View    
class DeleteCommentView(RedirectToProviousMixin, DeleteView):
    model = BlogComment
    template_name = 'comments/delete_comment.html'
###################################################################################################

   

#####-------------------- Update comment View
class UpdateCommentView(RedirectToProviousMixin, UpdateView):
    model = BlogComment
    template_name = 'comments/update_comments.html'
    form_class = EditCommentForm
###################################################################################################

templates/blog/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>

<section class="slider-area slider-area2">
<div class="slider-active">
<div class="single-slider slider-height2">
<div class="container">
<div class="row">
<div class="col-xl-8 col-lg-11 col-md-12">
<div class="hero__caption hero__caption2">
<h1 data-animation="bounceIn" data-delay="0.2s">About us</h1>

<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'courses:index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'base:about' %}">about</a></li>
</ol>
</nav>

</div>
</div>
</div>
</div>
</div>
</div>
</section>
<div class="services-area services-area2 section-padding40">
<div class="container">
<div class="row justify-content-sm-center">
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon1.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>60+ UX courses</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon2.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>Expert instructors</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
<div class="col-lg-4 col-md-6 col-sm-8">
<div class="single-services mb-30">
<div class="features-icon">
<img src="{% static 'assets/img/icon/icon3.svg' %}" alt="">
</div>
<div class="features-caption">
<h3>Life time access</h3>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
</div>
</div>
</div>

<section class="about-area1 fix pt-10">
<div class="support-wrapper align-items-center">
<div class="left-content1">
<div class="about-icon">
<img src="{% static 'assets/img/icon/about.svg' %}" alt="">
 </div>

<div class="section-tittle section-tittle2 mb-55">
<div class="front-text">
<h2 class="">Learn new skills online with top educators</h2>
<p>The automated process all your website tasks. Discover tools and
techniques to engage effectively with vulnerable children and young
people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Techniques to engage effectively with vulnerable children and young people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together. Online learning is as easy and natural.</p>
</div>
</div>
</div>
<div class="right-content1">

<div class="right-img">
<img src="{% static 'assets/img/gallery/about3.png' %}" alt="">
<div class="video-icon">
<a class="popup-video btn-icon" href="https://www.youtube.com/watch?v=up68UAfH0d0"><i class="fas fa-play"></i></a>
</div>
</div>
</div>
</div>
</section>


<div class="topic-area section-padding40">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-7 col-lg-8">
<div class="section-tittle text-center mb-55">
<h2>Explore top subjects</h2>
</div>
</div>
</div>
<div class="row">
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic1.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic2.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
 </div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic3.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic4.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic5.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic6.png' %}" alt="">
 <div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic7.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
<div class="col-lg-3 col-md-4 col-sm-6">
<div class="single-topic text-center mb-30">
<div class="topic-img">
<img src="{% static 'assets/img/gallery/topic8.png' %}" alt="">
<div class="topic-content-box">
<div class="topic-content">
<h3><a href="#">Programing</a></h3>
</div>
</div>
</div>
</div>
</div>
</div>
<div class="row justify-content-center">
<div class="col-xl-12">
<div class="section-tittle text-center mt-20">
<a href="courses.html" class="border-btn">View More Subjects</a>
</div>
</div>
</div>
</div>
</div>


<section class="about-area3 fix">
<div class="support-wrapper align-items-center">
<div class="right-content3">

<div class="right-img">
<img src="{% static 'assets/img/gallery/about3.png' %}" alt="">
</div>
</div>
<div class="left-content3">

<div class="section-tittle section-tittle2 mb-20">
<div class="front-text">
<h2 class="">Learner outcomes on courses you will take</h2>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Techniques to engage effectively with vulnerable children and young people.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world
learning together.</p>
</div>
</div>
<div class="single-features">
<div class="features-icon">
<img src="{% static 'assets/img/icon/right-icon.svg' %}" alt="">
</div>
<div class="features-caption">
<p>Join millions of people from around the world learning together.
Online learning is as easy and natural.</p>
</div>
</div>
</div>
</div>
</section>


<section class="team-area section-padding40 fix">
<div class="container">
<div class="row justify-content-center">
<div class="col-xl-7 col-lg-8">
<div class="section-tittle text-center mb-55">
<h2>Community experts</h2>
</div>
</div>
</div>
<div class="team-active">
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team1.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Urela</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team2.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Uttom</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team3.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Shakil</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team4.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. Arafat</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
<div class="single-cat text-center">
<div class="cat-icon">
<img src="{% static 'assets/img/gallery/team3.png' %}" alt="">
</div>
<div class="cat-cap">
<h5><a href="services.html">Mr. saiful</a></h5>
<p>The automated process all your website tasks.</p>
</div>
</div>
</div>
</div>
</section>

</main>

{% endblock %}

templates/blog/blog-grid.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<section class="ftco-section" id="scroll">
<div class="container-fluid">
<div class="row justify-content-center">
<div class="col-md-11 heading-section mb-5" data-aos="fade-up" data-aos-duration="1000">
<h2 class="mb-4">Our Blog</h2>
<p><span class="subheading mr-2"><a href="{% url 'home' %}">Home</a></span> <span class="subheading">Blog</span></p>
</div>
</div>
<div class="row">

    {% for BlogPost in object_list %}
<div class="col-md-3">
<div class="blog-entry justify-content-end" data-aos="fade-down" data-aos-duration="1000" data-aos-delay="100">
<a href="{% url 'BlogPost-details' BlogPost.slug %}" class="block-20 img" style="background-image:url({{ BlogPost.image.url }})">
</a>
<div class="list-team d-flex align-items-center">
<div class="d-flex align-items-center">
<div class="img" style="background-image:url({{ BlogPost.author.image.url }})"></div>
<h3 class="ml-2 mb-0">{{ BlogPost.author|title }}</h3>
</div>
<div class="text-right ion">
</div>
</div>
<div class="text">
<p class="meta"><span>{{ BlogPost.date_posted }} </span><a href="#">{{ BlogPost.comments.all|length}} Comments</a></p>
<h3 class="heading mb-3"><a href="{% url 'BlogPost-details' BlogPost.slug %}">{{ BlogPost.title|title }}</a mb-3=""></h3>
<p>{{ BlogPost.snippet|title }}</p>
</div>
</div>
</div>
    {% endfor %}

<div class="row mt-5">
<div class="col text-center">
<div class="block-27">
<ul>
    {% if is_paginated %}
    {% if page_obj.has_previous %}
<li><a href="#">&lt;</a></li>
{% endif %}
   
{% if page_obj.has_next %}
<li><a href="#">&gt;</a></li>
<a href="#!" class="next">&rarr;</a>
{% endif %}     
{% endif %}
</ul>


</div>
</div>
</div>
</div>
</section>
{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main>
<section class="slider-area slider-area2">
<div class="slider-active">
<div class="single-slider slider-height2">
<div class="container">
<div class="row">
<div class="col-xl-8 col-lg-11 col-md-12">
<div class="hero__caption hero__caption2">
<h1 data-animation="bounceIn" data-delay="0.2s">Company insights</h1>
<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'courses:index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'blog:bloglist' %}">Blog</a></li>
</ol>
</nav>

</div>
</div>
</div>
</div>
</div>
</div>
</section>

<section class="blog_area section-padding">
<div class="container">
<div class="row">
<div class="col-lg-8 mb-5 mb-lg-0">
<div class="blog_left_sidebar">

  {% for BlogPost in object_list %}

<article class="blog_item">
<div class="blog_item_img">
<img class="card-img rounded-0" src="{{ BlogPost.image.url }}" alt="">

<a href="{% url 'blog:BlogPost-details' BlogPost.slug %}" class="blog_item_date">
<h3>{{ BlogPost.date_posted }}</h3>
</a>
</div>
<div class="blog_details">
<a class="d-inline-block" href="{% url 'blog:BlogPost-details' BlogPost.slug %}">
<h2 class="blog-head" style="color: #2d2d2d;">{{ BlogPost.title|title }}</h2>
</a>
<p>{{ BlogPost.snippet|title }}</p>
<ul class="blog-info-link">
<li><a href="#"><i class="fa fa-user"></i> Travel, Lifestyle</a></li>
<li><a href="#"><i class="fa fa-comments"></i> {{ BlogPost.comments.all|length}} Comments</a></li>
</ul>
</div>
</article>

{% endfor %}


<nav class="blog-pagination justify-content-center d-flex">
<ul class="pagination">
<li class="page-item">
<a href="#" class="page-link" aria-label="Previous">
<i class="ti-angle-left"></i>
</a>
</li>
<li class="page-item">
<a href="#" class="page-link">1</a>
</li>
<li class="page-item active">
<a href="#" class="page-link">2</a>
</li>
<li class="page-item">
<a href="#" class="page-link" aria-label="Next">
<i class="ti-angle-right"></i>
</a>
</li>
</ul>
</nav>
</div>
</div>
<div class="col-lg-4">
<div class="blog_right_sidebar">
<aside class="single_sidebar_widget search_widget">
<form action="#">
<div class="form-group">
<div class="input-group mb-3">
<input type="text" class="form-control" placeholder='Search Keyword' onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">
<div class="input-group-append">
<button class="btns" type="button"><i class="ti-search"></i></button>
</div>
</div>
</div>
<button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn" type="submit">Search</button>
</form>
</aside>
<aside class="single_sidebar_widget post_category_widget">
<h4 class="widget_title" style="color: #2d2d2d;">Category</h4>
<ul class="list cat-list">
<li>
<a href="#" class="d-flex">
<p>Resaurant food</p>
<p>(37)</p>
</a>
</li>
<li>
<a href="#" class="d-flex">
<p>Travel news</p>
<p>(10)</p>
</a>
</li>
<li>
<a href="#" class="d-flex">
<p>Modern technology</p>
<p>(03)</p>
</a>
</li>
<li>
<a href="#" class="d-flex">
<p>Product</p>
<p>(11)</p>
</a>
</li>
<li>
<a href="#" class="d-flex">
<p>Inspiration</p>
<p>21</p>
</a>
</li>
<li>
<a href="#" class="d-flex">
<p>Health Care (21)</p>
<p>09</p>
</a>
</li>
</ul>
</aside>
<aside class="single_sidebar_widget popular_post_widget">
<h3 class="widget_title" style="color: #2d2d2d;">Recent Post</h3>
<div class="media post_item">
<img src="{% static 'assets/img/post/post_1.png' %}" alt="post">
<div class="media-body">
<a href="blog_details.html">
<h3 style="color: #2d2d2d;">From life was you fish...</h3>
</a>
<p>January 12, 2019</p>
</div>
</div>
<div class="media post_item">
<img src="{% static 'assets/img/post/post_2.png' %}" alt="post">
<div class="media-body">
<a href="blog_details.html">
<h3 style="color: #2d2d2d;">The Amazing Hubble</h3>
</a>
<p>02 Hours ago</p>
</div>
</div>
<div class="media post_item">
<img src="{% static 'assets/img/post/post_3.png' %}" alt="post">
<div class="media-body">
<a href="blog_details.html">
<h3 style="color: #2d2d2d;">Astronomy Or Astrology</h3>
</a>
<p>03 Hours ago</p>
</div>
</div>
<div class="media post_item">
<img src="{% static 'assets/img/post/post_4.png' %}" alt="post">
<div class="media-body">
<a href="blog_details.html">
<h3 style="color: #2d2d2d;">Asteroids telescope</h3>
</a>
<p>01 Hours ago</p>
</div>
</div>
</aside>
<aside class="single_sidebar_widget tag_cloud_widget">
<h4 class="widget_title" style="color: #2d2d2d;">Tag Clouds</h4>
<ul class="list">
<li>
<a href="#">project</a>
</li>
<li>
<a href="#">love</a>
</li>
<li>
<a href="#">technology</a>
</li>
<li>
<a href="#">travel</a>
</li>
<li>
<a href="#">restaurant</a>
</li>
<li>
<a href="#">life style</a>
</li>
<li>
<a href="#">design</a>
</li>
<li>
<a href="#">illustration</a>
</li>
</ul>
</aside>
<aside class="single_sidebar_widget instagram_feeds">
<h4 class="widget_title" style="color: #2d2d2d;">Instagram Feeds</h4>
<ul class="instagram_row flex-wrap">
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_5.png' %}" alt="">
</a>
</li>
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_6.png' %}" alt="">
</a>
</li>
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_7.png' %}" alt="">
</a>
</li>
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_8.png' %}" alt="">
</a>
</li>
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_9.png' %}" alt="">
</a>
</li>
<li>
<a href="#">
<img class="img-fluid" src="{% static 'assets/img/post/post_10.png' %}" alt="">
</a>
</li>
</ul>
</aside>
<aside class="single_sidebar_widget newsletter_widget">
<h4 class="widget_title" style="color: #2d2d2d;">Newsletter</h4>
<form action="#">
<div class="form-group">
<input type="email" class="form-control" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
</div>
<button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn" type="submit">Subscribe</button>
</form>
</aside>
</div>
</div>
</div>
</div>
</section>

</main>

{% endblock %}