base/urls.py
from django.urls import path
from base import views
    
app_name = 'base'

urlpatterns = [
    path('contact/', views.Contact.as_view(),name="contact"),
    path('about/', views.About.as_view(),name="about")
]

courses/urls.py
from django.urls import path

from courses import views

app_name = 'courses'

urlpatterns = [
    path('', views.course ,name="index"),
    path('courses/', views.course_display, name='courses'),
    path('<slug:slug>/', views.course_detail, name='course_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

vortex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('base/',include('base.urls', namespace='base')),
    path('blog/',include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('basket/', include('basket.urls', namespace='basket')),
]

courses/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from mptt.models import MPTTModel, TreeForeignKey
from cloudinary.models import CloudinaryField
from account.models import UserBase


class Category(models.Model):
    name = models.CharField(verbose_name=_("Category Name"), max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name =_("Category")
        verbose_name_plural =_("Categories")

    def get_absolute_url(self):
        return reverse("courses:category_list", args=[self.slug])

    def __str__(self):
        return self.name

class CourseAuthor(models.Model):
    user = models.OneToOneField(UserBase, related_name='teacher', on_delete=models.RESTRICT)
    image = CloudinaryField('image', null=True, blank=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    bio = models.CharField(max_length=2000)
    slug = models.SlugField(unique=True, max_length=100, null=True)

    def __str__(self):
        return str(self.user)

class Course(models.Model):
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(max_length=255)
    author = models.ForeignKey(CourseAuthor, on_delete=models.CASCADE)
    description = models.TextField(verbose_name=_("description"), blank=False)
    slug = models.SlugField(max_length=255, unique=True)
    regular_price = models.DecimalField(verbose_name=_("Regular Price"), max_digits=5, decimal_places=2)
    discount_price = models.DecimalField(verbose_name=_("Discount Price"), max_digits=5, decimal_places=2)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

    def get_absolute_url(self):
        return reverse("courses:course_detail", args=[self.slug])

    def __str__(self):
        return self.title

class CourseImage(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="course_image")
    image = CloudinaryField('image', null=True, blank=True)
    alt_text = models.CharField(max_length=255, null=True, blank=True)
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name =_("Course Image")
        verbose_name_plural = ("Course Images")

courses/views.py
from django.shortcuts import get_object_or_404, render
from courses.models import Category, Course
from django.views.generic import TemplateView


def course(request):
    courses = Course.objects.all()
    return render(request, 'index.html', {'courses': courses})

def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    courses = Product.objects.filter(category=category)
    return render(request, 'courses/category.html', {'category': category, 'courses': courses})

def course_detail(request, slug):
    course = get_object_or_404(Course, slug=slug, is_active=True)
    return render(request, 'courses/single.html', {'course': course})

def course_display(request):
    display = Course.objects.all()
    return render(request, 'courses/courses.html', {'display':display})

templates/courses/category.html
category

templates/courses/courses.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
<section class="slider-area slider-area2">
<div class="slider-active">
<div class="single-slider slider-height2">
<div class="container">
<div class="row">
<div class="col-xl-8 col-lg-11 col-md-12">
<div class="hero__caption hero__caption2">
<h1 data-animation="bounceIn" data-delay="0.2s">Our courses</h1>

<nav aria-label="breadcrumb">
<ol class="breadcrumb">
<li class="breadcrumb-item"><a href="{% url 'courses:index' %}">Home</a></li>
<li class="breadcrumb-item"><a href="{% url 'courses:courses' %}">Courses</a></li>
</ol>
</nav>

</div>
</div>
</div>
</div>
</div>
</div>
</section>

<div class="courses-area section-padding40 fix">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-7 col-lg-8">
                <div class="section-tittle text-center mb-55">
                    <h2>Our featured courses</h2>
                </div>
            </div>
        </div>

        <div class="row">
            {% for course in display %}
            <div class="col-lg-4 col-md-6">
                <div class="properties__card">
                    <div class="properties__img overlay1">
                        <a href="{{ course.get_absolute_url }}">
                            {% for image in course.course_image.all %}
                            {% if image.is_feature %}
                            <img src="{{ image.image.url }}" alt="">
                            {% endif %}
                            {% endfor %}
                        </a>
                    </div>
                    <div class="properties__caption">
                        <p>{{ course.category }}</p>
                        <h3><a href="{{ course.get_absolute_url }}">{{ course.title }}</a></h3>
                        <p>{{ course.description|slice:":50" }}</p>
                        <div class="properties__footer d-flex justify-content-between align-items-center">
                            <div class="restaurant-name">
                                <div class="rating">
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star"></i>
                                    <i class="fas fa-star-half"></i>
                                </div>
                                <p><span>(4.5)</span> based on 120</p>
                            </div>
                            <div class="price">
                                <span class="discounted-price">${{ course.discount_price }}</span>
                                <span class="regular-price">${{ course.regular_price }}</span>
                            </div>
                        </div>
                        <a href="{{ course.get_absolute_url }}" class="border-btn border-btn2">Purchase Course</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
    </main>

{%  endblock  %}

templates/courses/single.html
{% extends "base.html" %}
{% load static %}
{% block title %}
<title>{% if course %}{{ course.title }}{% endif %}</title>

{% endblock %}
{% block content %}

<main>
    <div class="courses-area section-padding40 fix">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-7 col-lg-8">
                    <div class="section-tittle text-center mb-55">
                        <h2>{{ course.title }}</h2>
                    </div>
                </div>
            </div>

            <div class="courses-actives">
                <div class="properties pb-20">
                    <div class="properties__card">
                        <div class="properties__img overlay1">
                            <a href="{{ course.get_absolute_url }}">
                                {% for image in course.course_image.all %}
                                    {% if image.is_feature %}
                                        <img src="{{ image.image.url }}" alt="">
                                    {% endif %}
                                {% endfor %}
                            </a>
                        </div>
                        <div class="properties__caption">
                            <p>{{ course.category }}</p>
                            <h3><a href="{{ course.get_absolute_url }}">{{ course.title }}</a></h3>
                            <p>{{ course.description }}</p>
                            <p>Author: {{ course.author }}</p>
                            <div class="properties__footer d-flex justify-content-between align-items-center">
                                <div class="restaurant-name">
                                    <div class="rating">
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star"></i>
                                        <i class="fas fa-star-half"></i>
                                    </div>
                                    <p><span>(4.5)</span> based on 120</p>
                                </div>
                                <div class="price">
                                    <span>${{ course.regular_price }}</span>
                                </div>
                            </div>
                            <a href="{{ course.get_absolute_url }}" class="border-btn border-btn2">Purchase Course</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock %}